receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      load:

processors:
  batch:
    timeout: 5s

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [debug]

